on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: rg-p2p-mailconf-env
      AZURE_ENV_NAME: dev  # Replace with your actual environment name
      AZURE_LOCATION: eastus  # Replace with your actual location
      FUNCTION_APP_NAME: <Your-FunctionApp-Name>  # Replace with your actual Function App name
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v1.0.0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Azure CLI
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az --version

      - name: Log in with Azure (Client Credentials)
        run: |
          echo $AZURE_CLIENT_SECRET > secret.txt
          azd auth login --client-id $AZURE_CLIENT_ID --client-secret $(<secret.txt) --tenant-id $AZURE_TENANT_ID
        shell: bash

      - name: Verify Login
        run: |
          az account show

      - name: Provision Infrastructure with Virtual Network
        run: azd provision --no-prompt
        env:
          AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ env.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
          USE_VIRTUAL_NETWORK_INTEGRATION: true
          USE_VIRTUAL_NETWORK_PRIVATE_ENDPOINT: true
          VIRTUAL_NETWORK_ADDRESS_SPACE_PREFIX: "10.1.0.0/16"
          VIRTUAL_NETWORK_INTEGRATION_SUBNET_ADDRESS_SPACE_PREFIX: "10.1.1.0/24"
          VIRTUAL_NETWORK_PRIVATE_ENDPOINT_SUBNET_ADDRESS_SPACE_PREFIX: "10.1.2.0/24"

      - name: Setup Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4

      - name: Deploy Azure Functions
        run: |
          cd C:\Users\apeccatiello\Desktop\P2PDeploymentTest-main\src\functions\uploadFunction
          func azure functionapp publish ${{ env.FUNCTION_APP_NAME }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
